### ISSUE TITLE
custom badge image upload is failing

### ISSUE THREAD

**Issue by seetharamayya** [assistx/openbadges#1]
Environment : IE 10 and Windows 8

How Found : Microsoft new SDET Bug Bash
Priority : 2
Seniority : 2

Steps:
![Badge_Upload_Failing](https://f.cloud.github.com/assets/3855738/260077/a685fb8a-8ccd-11e2-8756-2a4dbd5e44fb.PNG)

Navigate to https://msbackpack.azurewebsites.net/
then Click on Browse under badges panel
then select any image from locale system and then upload

Actual Result: Failing to upload 

Excepted Result: able to upload successfully

**Comment by kalalsherif** [comment]
We get a different error message in Safari "There was a problem saving your badge!"

**Comment by msousley** [comment]
this has been fixed in v1.0
