### ISSUE TITLE
Invalid Google Sign In Causes Internal Server Error

### ISSUE THREAD

**Issue by travismc1** [assistx/openbadges#12]
How Found: "Microsoft New SDET Bug Bash"
Priority: 3
Severity: 1
Description and Customer Impact: When user denies access once on Google, crashes OpenBadges site on return

Environment: Firefox
Repro Steps:
- Sign into OpenBadges (ie give your email)
- When given an option login with Google
- Provide your credentials. When it asks whether to allow the app, click "No Thanks"
- At 401 error page, click Back button (may not be necessary to repro bug)
- Now, anytime you try to go back and login with Google, you will get the internal server error   message.

Expected: A clear message indicating they did not allow access or that Google sign in failed.

**Comment by msousley** [comment]
This only happens if you "remember your approval" with Google.  If you do that, then google won't send us the login information and it will continue to fail until you go into Google and allow it.
