### ISSUE TITLE
Blank Email field error on Get Open Badge Page

### ISSUE THREAD

**Issue by tejasbansod** [assistx/openbadges#13]
Environment : IE 10 running on Windows 8

How Found - Microsoft New SDET Bug Bash
Priority - 2
Severity - 3
Description and Customer Impact - After entering a blank email address on http://msobitest.azurewebsites.net/ it throws an internal server error to the user which is not highlighted and does not inform the user that the email field is blank.

Repro Steps : 
1> Navigate to http://msobitest.azurewebsites.net/
2> Let the email field be blank.
3> Click "Get your open Badge".

Results: - It throws an Exception - System.Net.WebException: The remote server returned an error: (500) Internal Server Error. at System.Net.HttpWebRequest.GetResponse() at _Default.createAssertion() 

![Test1](https://f.cloud.github.com/assets/2066618/260166/ee4293c8-8ccf-11e2-9c06-68ee6361833d.PNG)

Expected :The user should be prompted the " email field cannot be blank . Please enter a valid email address. "

**Comment by msousley** [comment]
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
