### ISSUE TITLE
Email id containing just blank spaces is treated as valid on Microsoft Open Badges page.

### ISSUE THREAD

**Issue by swapnilsc** [assistx/openbadges#20]
Environment - Safari 5.1.7 browser
 How Found - Microsoft New SDET Bug Bash
 Priority - 2
 Severity - 2
 Description and Customer Impact - When "Get Your Open Badge" is clicked after entering just spaces (for eg. enter "                  ", in the email field without the quotes), a new badge is created even though the email id is invalid.
Repro Steps - 
•Navigate to the Microsoft open badges page - http://msobitest.azurewebsites.net/
*Enter blank spaces as email id 
•Click on "Get Your Open Badge"
Results - A new badge is created.
Expected - An error message should be shown to the user.

**Comment by msousley** [comment]
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
