### ISSUE TITLE
system does not indicates error msg when inputting an email address with "local-part" longer than 64.

### ISSUE THREAD

**Issue by ianXian** [assistx/openbadges#23]
How Found: Microsoft SDET bug bash

Priority: 2
Severity: 2

Description: 

The system does not respond with an email address whose "local-part" longer than 64 characters

Repro:

*Navigate to http://msobitest.azurewebsites.net/
*input an email address with local-part longer than 64 (the maximum of the local part of an email address is 64).
*System does not pop up any error.

**Comment by msousley** [comment]
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
