### ISSUE TITLE
system does not show error msg when using an email address with domain part longer than 256

### ISSUE THREAD

**Issue by ianXian** [assistx/openbadges#26]
![image](https://f.cloud.github.com/assets/3846072/260260/23768200-8cd2-11e2-9d98-ef99cd7f3dd8.png)

How Found: Microsoft SDET bug bash

Priority: 2

Severity: 2

Description: When inputting an email address with the domain part longer than 256 characters, the system does not show any error msg.

Repro:
- Navigate to http://msobitest.azurewebsites.net/
- Input an email address with domain part longer than 256 characters ( that's the maximum).
- the system does not pop up any error msg.

**Comment by kalalsherif** [comment]
Similarily, an email name over 256 characters is accepted when it should give an error (ex. 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@email.com)

**Comment by msousley** [comment]
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
