### ISSUE TITLE
system does not indicate error msg when inputting an email address longer than 256.

### ISSUE THREAD

**Issue by ianXian** [assistx/openbadges#32]
How found: Microsoft SDET bug bash

Priority: 2

Severity: 2

Description: The system does not respond to an invalid email address with more than 256 letters

Repro:
- Navigate to http://msobitest.azurewebsites.net/
- input an email address with more than 256 letters
- the system does not pop up any error msg

**Comment by msousley** [comment]
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
