### ISSUE TITLE
AW-9: S2/P1: Support Email Has No Diagnostic Log

### ISSUE THREAD

**Issue by danielbae** [assistx/openbadges#320]
apParent Windows 1.0.5

-Sent with Outlook, no diag log
-Sent from Windows mail, does have diag log

Date Found: 10/11/17

**Comment by aloh86** [comment]
This is expected. Apparently, e-mail attachments cannot be sent from one UWP app to a Win32 app like Outlook. Windows mail is a UWP app, so it works, but not Outlook.

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/5a539ff6-ce81-4f05-83a0-8bf430d827f8/uwpwindows-10-c-universal-windows-app-email-with-attachment?forum=wpdevelop

**Comment by danielbae** [comment]
Ok thanks! Ill close this bug

Daniel
________________________________
