### ISSUE TITLE
CP-204: S2/P3: URL Capture Is Not Capturing Website

### ISSUE THREAD

**Issue by danielbae** [assistx/openbadges#324]
3.11.0.1
v97

Case 1:
->Start class
->Select Hallie only
->Start URL Capture
->On Hallie, open Chrome and then open cnn.com
->Stop Web Capture
->->cnn.com and its components are not listed, even if cnn.com was given sufficient time to finish loading

Case 2:
->Start class
->Allow both Irwin and Hallie to be controlled
->Repro above steps, bug still exists

In both cases 1 and 2, the URL Capture captures the Chrome homepage components

Case 3: Visit no website
->->Chrome components are being listed. Furthermore, the timestamps are wrong: it lists 6:20pm as the time accessed, when the current time is 7:16pm

This bug did not exist for Simulation Mode

Count: 3/3

![screenshot 13](https://user-images.githubusercontent.com/25756681/31527266-dd9efa88-af80-11e7-92ad-571c1e8d1258.png)
![screenshot 14](https://user-images.githubusercontent.com/25756681/31527406-d33f9ea2-af81-11e7-8d17-c6197ef6e405.png)

Date found: 10/12/17

Date found: 1.27.18

**Comment by danpark** [comment]
do not start class it does not work when class started

Sent from my iPhone

On Oct 12, 2017, at 7:09 PM, danielbae <notifications@github.com<mailto:notifications@github.com>> wrote:


3.11.0.1
v97

->Start class
->Select Hallie only
->Start URL Capture
->On Hallie, open Chrome and then open cnn.com<http://cnn.com>
->Stop Web Capture
->->cnn.com<http://cnn.com> and its components are not listed, even if cnn.com<http://cnn.com> was given sufficient time to finish loading

Count: 3/3

[screenshot 13]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25756681%2F31527266-dd9efa88-af80-11e7-92ad-571c1e8d1258.png&data=02%7C01%7Cdhpark%40hotmail.com%7Ca282f17b5fd74c0db6ae08d511df72fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636434573750086874&sdata=u9UzOcZ4x%2BTd3NjeEFi0NSw7o5ATkV5bIzR6SUb31ZQ%3D&reserved=0>

Date found: 10/12/17

**Comment by danielbae** [comment]
Ok

Daniel
