### ISSUE TITLE
Unable to signout of gmail account

### ISSUE THREAD

**Issue by deesha** [assistx/openbadges#33]
Environment: Google Chrome

Severity: 1 
Priority: 1

Repro Steps:
1. Login to gmail
2. Then Sign out
3. Then select the Sign in with Azure and select gmail
4. It directly signs in and shows the file upload page 

Expected: To show the gmail sign in page

**Comment by ru2dvs** [comment]
Seems like a repeat of Issue #30.  Updated #30 to indicate that issue is reproed in Chrome

**Comment by deesha** [comment]
It is a different issue where I am clicking on the sign out button but still it is logged in, not on the "I am not .." option.

**Comment by ru2dvs** [comment]
Ah I see.  My bad and thank you for the explanation!

**Comment by msousley** [comment]
Duplicate of Issue #18

**Comment by msousley** [comment]
closed the issue in b7ee75f just now
