### ISSUE TITLE
Capital and lower case email address (same one) should be treated as same one.

### ISSUE THREAD

**Issue by ianXian** [assistx/openbadges#4]
![image](https://f.cloud.github.com/assets/3846072/260074/8ec5890c-8ccd-11e2-8bbd-5bb6061f9032.png)

How Found - Microsoft New SDET Bug Bash

Priority:  1
Severity: 2

Repro:
- Claim one badge with a valid email address, use some capital letters.
- login with the same address
- System displays "the badge was not awarded to you".

**Comment by msousley** [comment]
The openbadges site itself always pushes emails to lower case, the test badge site however did not.  This is fixed in the openbadges_testsite repository
