### ISSUE TITLE
email address with comments are not allowed 

### ISSUE THREAD

**Issue by ianXian** [assistx/openbadges#42]
How found: Microsoft SDET bug bash

Priority: 2

Severity: 2

description: an email address with comments on either side of the local part is allowed, e.g. smith(comment)@example.com is a valid one, which equals to smith@example.com
But the system still pops up errors

Repro:

*Navigate to http://msobitest.azurewebsites.net/
*enter an email address with comment such as smith(comment)@example.com
*system pops up error saying it is not valid email address

**Comment by msousley** [comment]
fixed with this checkin https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
