### ISSUE TITLE
Cannot Upload Badges in Firefox

### ISSUE THREAD

**Issue by benkur** [assistx/openbadges#43]
Environment: Firefox v19.0.2

How Found - Microsoft New SDET Bug Bash
 Priority - 2
 Severity - 2

Description and Customer Impact -
Badges cannot be uploaded from Firefox at all.

Repro Steps -
Upload a badge using Firefox ( we had version 19.0.2).  This is happening 100% of the time for me in Firefox.

Result - 
Error that says: "This seems to be an invalid url (or there was a DNS error): "

Expected - 
Badge upload accepted.

**Comment by lilian-wang** [comment]
Duplicate of Issue https://github.com/assistx/openbadges/issues/22

**Comment by msousley** [comment]
Only actual badges can be uploaded.  Error description has been updated in v1.0 to say the badge does not have the baked in parts
