### ISSUE TITLE
Group name mismatch if the name is edited from both the Home Page and Share Group Page.

### ISSUE THREAD

**Issue by swapnilsc** [assistx/openbadges#46]
Environment - Safari 5.1.7 browser
 How Found - Microsoft New SDET Bug Bash
 Priority - 2
 Severity - 2
 Description and Customer Impact -  
•Login to your Open Badge account.
*Create a Group by dragging a badge to the box.
*Rename the group on the Home Page by clicking the current name which by default is "New Group"
*Click on Share this group button.
*Click on Edit this page button
*Edit the name to something different from that on the home page.
*Go back to Home page.
Results - The Group name on home page is unchanged even after changing it on Share this group page.
 Expected - .The group names should be consistent on both the pages.

**Comment by msousley** [comment]
These are actually disconnected.  In your "home page" view, this is your name for the group.  In the share view this is the "Shared" name for the group.
