### ISSUE TITLE
The invalid url error message cannot be hidden as the close button does not work.

### ISSUE THREAD

**Issue by suneetsasidharan** [assistx/openbadges#50]
```
Environment - Win8 and Google Chrome
How Found - Microsoft New SDET Bug Bash
Priority - 3
Severity - 3
Description and Customer Impact - Customer is unable to hide the error message. 
Repro Steps - 
• Enter an email address to get badges
```

• Login using the any of the 4 working login methods
• Click on "Cool, Lets go"
• Go ahead and accept the badges by clicking "Yup"
• Try and upload a custom badge in the next page.
- Try to close the error message.
  
  Results - The error message does not subside
  Expected - The error message subsides
  ![Close](https://f.cloud.github.com/assets/1211718/260561/8aacdef0-8cd8-11e2-9150-23e841f2bc06.jpg)

**Comment by msousley** [comment]
fixed in v1.0
