### ISSUE TITLE
Entering invalid email to receive open badge

### ISSUE THREAD

**Issue by mariobarba** [assistx/openbadges#6]
Environment - 
IE 10, Classic Interface, Win 8

Priority - 3

Severity - 3

Description and Customer Impact - 
When trying to register to http://msobitest.azurewebsites.net/ the client could enter an invalid email address by error and go trough the process without knowing it.

Repro Steps - 
-Open IE 10 on classic interface
-Navigate to http://msobitest.azurewebsites.net/
-Type an email address with an invalid domain extension. (Ex. tester@hotmail.commmm)

Results - 
- Its allowed as a valid email address

Expected - 
- It should show "Contact must be a valid email address if supplied"

**Comment by kalalsherif** [comment]
Found under Safari as well. Likely browser independent.

**Comment by msousley** [comment]
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924
