### ISSUE TITLE
Testability: Assertions should display on the page being shown to the user, not the previous page

### ISSUE THREAD

**Issue by brucecrms** [assistx/openbadges#7]
Environment: IE9 and IE 10 running on Windows 7, 8, and RT

How Found - Microsoft New SDET Bug Bash

Priority - 3
Severity - 3

Description and Customer Impact - This assertion appears on the page just after the user click the control to move to the next page.  The next page quickly replaces the old one, making it very hard to notice the assertion.

Repro Steps -

Navigate to http://msobitest.azurewebsites.net/
- Type an email address
- Click ((Get Your Open Badge))

Results - Assertion 803bc1 ca74f6b9c5acd5a056cde49795 appears very quickly and then disappears as the next page is displayed.

Expected - The assertion should be obvious to the user.  For example:
- Show the assert on the next page
- Pop up the assert in a pop-up

**Comment by msousley** [comment]
This is mainly for debugging purposes.  The badge you see on the backpack page is the assertion.  Not going to fix this
